### ISSUE TITLE
version 0.0.3 stoped working in my C7 V2 170525

### ISSUE THREAD

**Issue by martindb** [ericpignet/home-assistant-tplink_router#6]
Version  0.0.2 works great.

Log error with version 0.0.3:

Logger: homeassistant.components.device_tracker
Source: custom_components/tplink_router/device_tracker.py:537
Integration: Device tracker (documentation, issues)
First occurred: 3:23:45 PM (1 occurrences)
Last logged: 3:23:45 PM

Error setting up platform legacy
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/device_tracker/setup.py", line 64, in async_setup_legacy
    self.platform.get_scanner, hass, {DOMAIN: self.config}
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/tplink_router/device_tracker.py", line 54, in get_scanner
    scanner = cls(config[DOMAIN])
  File "/config/custom_components/tplink_router/device_tracker.py", line 513, in __init__
    super(Tplink6DeviceScanner, self).__init__(config)
  File "/config/custom_components/tplink_router/device_tracker.py", line 81, in __init__
    self.success_init = self._update_info()
  File "/config/custom_components/tplink_router/device_tracker.py", line 679, in _update_info
    gotToken = self._get_auth_tokens()
  File "/config/custom_components/tplink_router/device_tracker.py", line 613, in _get_auth_tokens
    pubkey = self._get_pub_key()
  File "/config/custom_components/tplink_router/device_tracker.py", line 537, in _get_pub_key
    e = int(ee, 16)
ValueError: invalid literal for int() with base 16: ''

**Comment by ericpignet** [comment]
Sorry about that. Unsafe conversion in pull request #4 .
It didn't happen for me because the previous query was failing cleanly, before this conversion.
Should be fixed with last commit (see above).
I released a v0.0.4, please let me know if it's fixed

**Comment by martindb** [comment]
Great, thank you. It seems that it's solved.
